name: surface_sampling
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - python=3.8
  - matplotlib
  - pandas
  - pre-commit
  - pylint
  - ipykernel
  - notebook
  - ase
  - lammps=v2021.09.21
  - pip
  - pip:
    - ipykernel
    - git+https://github.com/SUNCAT-Center/CatKit.git
