name: surface_sampling
channels:
  - conda-forge
  - defaults
dependencies:
  - gym
  - flake8
  - python
  - scikit-learn
  - matplotlib
  - pandas
  - pytorch
  - pylint
  - ipykernel
  - notebook
  - ase
