name: surface_sampling
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - flake8
  - python=3.8
  - pytorch=2.0
  - pytorch-cuda=11.7
  - matplotlib
  - numpy>=1.21.6,<=1.22.4
  - pandas
  - pre-commit
  - pylint
  - ipykernel
  - notebook
  - ase
  - pymatgen=2023.5.10
  - rdkit
  - e3fp
  - scikit-learn
  - lammps
  - openkim-models
  - pip
  - pip:
    - git+https://github.com/SUNCAT-Center/CatKit.git
